
export const markets: string[] = [
    'BTC-USDT',
    'BTC3L-USDT',
    'BTC3S-USDT',
    'ETH-USDT',
    'ETH3L-USDT',
    'ETH3S-USDT',
    'ADA-USDT',
    'ADA3L-USDT',
    'ADA3S-USDT',
    'EOS-USDT',
    'EOS3L-USDT',
    'EOS3S-USDT',
    'BCH-USDT',
    'BCH3L-USDT',
    'BCH3S-USDT',
    'VET-USDT',
    'VET3L-USDT',
    'VET3S-USDT',
    'LTC-USDT',
    'LTC3L-USDT',
    'LTC3S-USDT',
    'XRP-USDT',
    'XRP3L-USDT',
    'XRP3S-USDT',
    'DOGE-USDT',
    'DOGE3L-USDT',
    'DOGE3S-USDT',
    'SOL-USDT',
    'SOL3L-USDT',
    'SOL3S-USDT',
    'LINK-USDT',
    'LINK3L-USDT',
    'LINK3S-USDT',
    'DOT-USDT',
    'DOT3L-USDT',
    'DOT3S-USDT',
    'ATOM-USDT',
    'ATOM3L-USDT',
    'ATOM3S-USDT',
    'UNI-USDT',
    'UNI3L-USDT',
    'UNI3S-USDT',
    'AXS-USDT',
    'AXS3L-USDT',
    'AXS3S-USDT',
    'FTM-USDT',
    'FTM3L-USDT',
    'FTM3S-USDT',
    'BNB-USDT',
    'BNB3L-USDT',
    'BNB3S-USDT',
    'MATIC-USDT',
    'MATIC3L-USDT',
    'MATIC3S-USDT',
    'SUSHI-USDT',
    'SUSHI3L-USDT',
    'SUSHI3S-USDT',
    'NEAR-USDT',
    'NEAR3L-USDT',
    'NEAR3S-USDT',
    'AAVE-USDT',
    'AAVE3L-USDT',
    'AAVE3S-USDT',
    'SAND-USDT',
    'SAND3L-USDT',
    'SAND3S-USDT',
    'AVAX-USDT',
    'AVAX3L-USDT',
    'AVAX3S-USDT',
    'MANA-USDT',
    'MANA3L-USDT',
    'MANA3S-USDT',
    'KCS-USDT'
];

export const marketsPriceLength: {
    [key: string]: {
        before: number;
        after: number;
    }
} = {
    'BTC-USDT': {before: 6, after: 1},
    'BTC3L-USDT': {before: 2, after: 6},
    'BTC3S-USDT': {before: 3, after: 4},
    'ETH-USDT': {before: 5, after: 2},
    'ETH3L-USDT': {before: 2, after: 6},
    'ETH3S-USDT': {before: 2, after: 6},
    'ADA-USDT': {before: 2, after: 6},
    'ADA3L-USDT': {before: 3, after: 6},
    'ADA3S-USDT': {before: 2, after: 4},
    'EOS-USDT': {before: 2, after: 4},
    'EOS3L-USDT': {before: 2, after: 6},
    'EOS3S-USDT': {before: 2, after: 4},
    'BCH-USDT': {before: 4, after: 2},
    'BCH3L-USDT': {before: 2, after: 6},
    'BCH3S-USDT': {before: 2, after: 4},
    'VET-USDT': {before: 2, after: 7},
    'VET3L-USDT': {before: 2, after: 6},
    'VET3S-USDT': {before: 2, after: 4},
    'LTC-USDT': {before: 3, after: 3},
    'LTC3L-USDT': {before: 2, after: 6},
    'LTC3S-USDT': {before: 2, after: 4},
    'XRP-USDT': {before: 2, after: 5},
    'XRP3L-USDT': {before: 2, after: 6},
    'XRP3S-USDT': {before: 2, after: 4},
    'DOGE-USDT': {before: 0, after: 5},
    'DOGE3L-USDT': {before: 2, after: 6},
    'DOGE3S-USDT': {before: 2, after: 4},
    'SOL-USDT': {before: 3, after: 3},
    'SOL3L-USDT': {before: 2, after: 6},
    'SOL3S-USDT': {before: 2, after: 4},
    'LINK-USDT': {before: 2, after: 4},
    'LINK3L-USDT': {before: 2, after: 6},
    'LINK3S-USDT': {before: 2, after: 4},
    'DOT-USDT': {before: 2, after: 4},
    'DOT3L-USDT': {before: 2, after: 6},
    'DOT3S-USDT': {before: 2, after: 4},
    'ATOM-USDT': {before: 3, after: 4},
    'ATOM3L-USDT': {before: 2, after: 6},
    'ATOM3S-USDT': {before: 2, after: 4},
    'UNI-USDT': {before: 2, after: 4},
    'UNI3L-USDT': {before: 2, after: 6},
    'UNI3S-USDT': {before: 2, after: 4},
    'AXS-USDT': {before: 3, after: 3},
    'AXS3L-USDT': {before: 2, after: 3},
    'AXS3S-USDT': {before: 2, after: 4},
    'FTM-USDT': {before: 2, after: 5},
    'FTM3L-USDT': {before: 2, after: 6},
    'FTM3S-USDT': {before: 2, after: 4},
    'BNB-USDT': {before: 4, after: 3},
    'BNB3L-USDT': {before: 2, after: 4},
    'BNB3S-USDT': {before: 2, after: 4},
    'MATIC-USDT': {before: 2, after: 4},
    'MATIC3L-USDT': {before: 2, after: 6},
    'MATIC3S-USDT': {before: 2, after: 4},
    'SUSHI-USDT': {before: 2, after: 4},
    'SUSHI3L-USDT': {before: 2, after: 6},
    'SUSHI3S-USDT': {before: 2, after: 4},
    'NEAR-USDT': {before: 2, after: 4},
    'NEAR3L-USDT': {before: 2, after: 6},
    'NEAR3S-USDT': {before: 2, after: 6},
    'AAVE-USDT': {before: 3, after: 3},
    'AAVE3L-USDT': {before: 2, after: 6},
    'AAVE3S-USDT': {before: 2, after: 4},
    'SAND-USDT': {before: 2, after: 5},
    'SAND3L-USDT': {before: 2, after: 6},
    'SAND3S-USDT': {before: 2, after: 6},
    'AVAX-USDT': {before: 3, after: 3},
    'AVAX3L-USDT': {before: 2, after: 6},
    'AVAX3S-USDT': {before: 2, after: 4},
    'MANA-USDT': {before: 2, after: 5},
    'MANA3L-USDT': {before: 2, after: 6},
    'MANA3S-USDT': {before: 2, after: 4},
    'KCS-USDT': {before: 3, after: 3}
};
